/**
 *
 * @author Berker Acir
 */
public enum Action {
    // SMELTER Actions
    SMELTER_CREATED,
    SMELTER_STARTED,
    SMELTER_FINISHED,
    SMELTER_STOPPED,

    // CONSTRUCTOR Actions
    CONSTRUCTOR_CREATED,
    CONSTRUCTOR_STARTED,
    CONSTRUCTOR_FINISHED,
    CONSTRUCTOR_STOPPED,

    // TRANSPORTER Actions
    TRANSPORTER_CREATED,
    TRANSPORTER_TRAVEL,
    TRANSPORTER_TAKE_INGOT,
    TRANSPORTER_DROP_INGOT,
    TRANSPORTER_STOPPED
}
